overtime/urls.py
'''
Module that maps incoming URL requests to functions which return responses
'''

from django.conf.urls import patterns, include, url
from django.contrib import admin
from timetracker.overtime import views

urlpatterns = patterns('',
                       (r'accept_edit/(?P<entry>\d+)/?$', views.accept_edit),
                       (r'accepted/?$', views.accepted),
                       (r'approval_list/?$', views.approval_list),
)

reporting/urls.py
from django.conf.urls import patterns, include, url

from timetracker.reporting import views
from timetracker.utils.datemaps import gen_team_list

YEAR = '(?P<year>\d{4})'
MONTH = '(?P<month>\d{1,2})'
TEAM = '(?P<team>%s)'

TEAM = TEAM % gen_team_list()

urlpatterns = patterns(
    '',
    url(r'^/?$', views.reporting),
    url(r'^all/(?P<who>\d+)/?$', views.download_all_holiday_data),
    url(r'^yearmonthhol/%s/%s/?$' % (YEAR, MONTH), views.yearmonthhol),
    url(r'^ot_by_month/%s/%s/?$' % (YEAR, MONTH), views.ot_by_month),
    url(r'^ot_for_hr/%s/%s/?$' % (YEAR, MONTH), views.ot_for_hr),
    url(r'^ot_by_year/%s/?$' % YEAR, views.ot_by_year),
    url(r'^hols_for_yearmonth/%s/?$' % YEAR, views.holidays_for_yearmonth),
    url(r'^all_team/%s/%s/%s/?$' % (YEAR, MONTH, TEAM), views.all_team),
)

urls.py
'''
Module that maps incoming URL requests to functions which return responses
'''

from django.conf.urls import patterns, include, url
from django.contrib import admin

from tastypie.api import Api

from timetracker import views
from timetracker.tracker.models import Tbluser
from timetracker.tracker.api import (TbluserResource, resources,
                                     TrackingEntryResource)
from timetracker.vcs.api import ActivityEntryResource
from timetracker.utils.datemaps import gen_process_list

admin.autodiscover()

api = Api(api_name='v1')
for resource in resources:
    api.register(resource())

api.register(TbluserResource())
api.register(TrackingEntryResource())
api.register(ActivityEntryResource())

YEAR = '(?P<year>\d{4})'
MONTH = '(?P<month>\d{1,2})'
DAY = '(?P<day>\d{1,2})'
PROCESS = '/?(?P<process>%s)?'


PROCESS = PROCESS % gen_process_list()

# todo: tracker app needs to be made into it's own
#       app and then the main views in here will
#       just point to that.
urlpatterns = patterns('',
    url(r'^$', views.index),

    url(r'^calendar/?$', views.user_view),
    url(r'^calendar/%s/?$' % YEAR, views.user_view),
    url(r'^calendar/%s/%s/?$' % (YEAR, MONTH), views.user_view),
    url(r'^calendar/%s/%s/%s/?$' % (YEAR, MONTH, DAY), views.user_view),

    url(r'^holiday_planning%s$' % PROCESS,
        views.view_with_holiday_list,
        {"template":"holidays.html", "admin_required": True}),
    url(r'^holiday_planning/%s/%s%s$' % (YEAR, MONTH, PROCESS),
        views.view_with_holiday_list,
        {"template":"holidays.html", "admin_required": True}),

    url(r'^team_planning/?$', views.view_with_holiday_list,
        {"template":"team_planning.html"}),
    url(r'^team_planning/%s/%s/?$' % (YEAR, MONTH),
        views.view_with_holiday_list,
        {"template":"team_planning.html"}),

    url(r'^yearview/?(?P<who>\d+)?$', views.yearview),
    url(r'^yearview/?(?P<who>\d+)/%s/?$' % YEAR, views.yearview),

    url(r'^overtime/?(?P<who>\d+)?$', views.overtime),
    url(r'^overtime/?(?P<who>\d+)/%s/?$' % YEAR, views.overtime),

    url(r'^admin_view/?$', views.view_with_employee_list,
        {"template":"admin_view.html"}),
    url(r'^ajax/?$', views.ajax),
    url(r'^login/?$', views.login),
    url(r'^logout/?$', views.logout),
    url(r'^user_edit/?$', views.view_with_employee_list,
        {"template":"useredit.html","get_all":True}),
    url(r'^edit_profile/?$', views.edit_profile),
    url(r'^explain/?$', views.explain),
    url(r'^forgot_my_password/?$', views.forgot_pass),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    (r'^reporting/', include('timetracker.reporting.urls')),
    (r'^ot/', include('timetracker.overtime.urls')),
    (r'^vcs/', include('timetracker.vcs.urls')),
    (r'^indeng/', include('timetracker.industrial_engineering.urls')),

    (r'^api/', include(api.urls)),
)

vcs/urls.py
'''
Module that maps incoming URL requests to functions which return responses
'''

from django.conf.urls import patterns, include, url
from timetracker.vcs import views

urlpatterns = patterns('',
                       (r'insert/?$', views.vcs),
                       (r'inserted/?$', views.vcs_add),
                       (r'entries', views.entries),
                       (r'update', views.update),
                       (r'report_upload', views.report_upload),
)

reporting/models.py
from django.db import models

# Create your models here.

vcs/models.py
from collections import defaultdict, OrderedDict
from datetime import datetime
from decimal import Decimal

from django.db import models
from django.core.cache import cache

from timetracker.utils.datemaps import ABSENT_CHOICES, group_for_team


COSTBUCKETS = (
    ('PVA', 'Processing Value Add'),
    ('PVE', 'Processing Value Enabling'),
    ('PNVE', 'Processing Non Value Add'),
    ('QAPP', 'Quality Appresial'),
    ('QPR', 'Quality Prevention'),
    ('QIF', 'Quality Internal Failure'),
    ('QIFPQ', 'Quality Internal Failure Process Quality'),
    ('QIFPI', 'Quality Internal Failure Poor Input Quality'),
    ('QIFRC', 'Quality Internal Failure Rework Cost'),
    ('QEF', 'Quality External Failure'),
    ('QEFQR', 'Quality External Failure Query Resolution'),
    ('QEFER', 'Quality External Failure External Rework'),
    ('QEFCE', 'Quality External Failure Customer Escalations'),
    ('COUTT', 'Cost of Under Utilization Non Transactional Time'),
    ('COUUL', 'Cost of Under Utilization Unavoidable Loss'),
    ('COUAL', 'Cost of Under Utilization Avoidable Loss'),
)


class Activity(models.Model):
    """Activity encapsulates the idea of a single task for Industrial
    Engineering purposes.

    Group: This is the concatenation of the account and the process
    this is used to find which employees a particular activity is
    aimed at.

    Group Type: This is the category in which a particular activity
    resides

    Group Detail: This is similar to a sub-category, this gives a lot
    more details on what the Activity is.

    Details: This shows what the volume represents when you create a
    related ActivityEntry.

    Disabled: Currently unused.

    Time: the time factor for this Activity, how long it takes to
    process.
    """

    group = models.CharField(max_length=4)
    grouptype = models.CharField(max_length=100)
    groupdetail = models.CharField(max_length=100)
    details = models.CharField(max_length=256)
    disabled = models.BooleanField()
    time = models.DecimalField(decimal_places=2, max_digits=10)
    costbucket = models.CharField(max_length=5, choices=COSTBUCKETS)

    def __unicode__(self): # pragma: no cover
        return u"%s - %s - %s - %s" % (self.group,
                                       self.grouptype,
                                       self.groupdetail,
                                       self.details)

    class Meta:
        unique_together = (("group", "grouptype", "groupdetail", "time"),)
        verbose_name_plural = "Activities"

class ActivityEntry(models.Model):
    """ActivityEntry allows us to join together a single Activity along
    with the user, amount and creation date of when the Activity took
    place.

    User: This is the user associated with this particular
    ActivityEntry.

    Activity: An instance of the Activity this ActivityEntry is linked
    to.

    Amount: an integer representing how many of that particular
    Activity was completed.

    Creation Date: The date that this ActivityEntry was created.
    """
    user = models.ForeignKey(
        'tracker.Tbluser',
        related_name="user_foreign"
    )
    activity = models.ForeignKey(
        Activity,
        related_name="activity_foreign"
    )
    amount = models.BigIntegerField()
    creation_date = models.DateField()

    def time(self): # pragma: no cover
        return self.activity.time * self.amount

    def __unicode__(self): # pragma: no cover
        return u'%s - %s - %d' % (self.user, self.activity, self.time())

    @staticmethod
    def filterforyearmonth(teams, year=None, month=None):
        # to prevent circular imports
        from timetracker.tracker.models import TrackingEntry
        if year is None: # pragma: no cover
            year = datetime.today().year
        if month is None: # pragma: no cover
            month = datetime.today().month

        invalidset = defaultdict(list)
        [invalidset[entry.user.id].append(entry.id)
         for entry in TrackingEntry.objects.filter(
                daytype__in=["PUABS", "DAYOD"]
         ).select_related("user")]

        def invalid(entry): # pragma: no cover
            return entry.id in invalidset[entry.user.id]

        return ActivityEntry.objects.filter(
            user__market__in=teams,
            creation_date__year=year,
            creation_date__month=month
        ).select_related("activity", "user"), invalid

    @staticmethod
    def costbucket_count(teams, year=None, month=None):
        entries, _ = ActivityEntry.filterforyearmonth(teams, year, month)
        costbuckets = defaultdict(int)
        for entry in entries:
            costbuckets[entry.activity.costbucket] += 1
        return costbuckets

    @staticmethod
    def utilization_calculation(teams, year=None, month=None):
        if year is None: # pragma: no cover
            year = datetime.today().year
        if month is None: # pragma: no cover
            month = datetime.today().month

        cached_result = cache.get("utilization:%s%s%s" % (''.join(teams), year, month))
        if cached_result: # pragma: no cover
            return cached_result

        # prevent circular imports
        from timetracker.utils.calendar_utils import working_days
        from timetracker.tracker.models import Tbluser, TrackingEntry

        entries, invalid = ActivityEntry.filterforyearmonth(teams, year, month)
        if len(entries) == 0:
            return {
                "util": {
                    "percent": 0,
                    "target": 65
                },
                "effi": {
                    "percent": 0,
                    "target": 85
                },
                "avai": {
                    "percent": 0,
                    "target": 80
                },
                "FTE": 0
            }

        effi, util = (0, 0)
        users = set()
        losses = TrackingEntry.objects.filter(user__market__in=teams,
                                              daytype=["PUABS", "DAYOD", "HOLIS"],
                                              entry_date__year=year,
                                              # 460 is a single
                                              # industrial engineering
                                              # FTE in Minutes.
                                              entry_date__month=month).count() * 460
        for entry in entries:
            if invalid(entry): # pragma: no cover
                continue
            time = entry.amount * entry.activity.time
            if entry.activity.group != "ALL":
                util += time
            else: # pragma: no cover
                losses += time
            effi += time

            # so we can see how many FTE's we had during this month.
            users.add(entry.user)

        available_time = (Tbluser.available_minutes(teams) * len(working_days(year, month)))
        utilization_percent = (100 * (Decimal(util) / Decimal(available_time)))
        efficiency_percent = (100 * (Decimal(util) / (Decimal(available_time) - Decimal(losses))))
        availability_percent = (100 * (Decimal(available_time) - Decimal(losses)) / Decimal(available_time))

        res = {
            "util": {
                "percent": utilization_percent,
                "target": 65
            },
            "effi": {
                "percent": efficiency_percent,
                "target": 85
            },
            "avai": {
                "percent": availability_percent,
                "target": 80
            },
            "FTE": len(users)
        }
        cache.set("utilization:%s%s%s" % (''.join(teams), year, month), res)
        return res

    @staticmethod
    def utilization_last_12_months(teams, year=None, month=None):
        from timetracker.utils.calendar_utils import last12months

        if year is None: # pragma: no cover
            year = datetime.today().year
        if month is None: # pragma: no cover
            month = datetime.today().month

        dates = last12months(year, month)
        utilization = OrderedDict()
        for date in dates:
            utilization[date] = ActivityEntry.utilization_calculation(
                teams, date.year, date.month
            )
        return utilization, dates

    @staticmethod
    def activity_volumes(teams, year=None, month=None, activity=None):
        if year is None: # pragma: no cover
            year = datetime.today().year
        if month is None: # pragma: no cover
            month = datetime.today().month

        cached_result = cache.get("activity_volumes:%s%s%s%s" % (''.join(teams), year, month, activity))
        if cached_result: # pragma: no cover
            return int(cached_result)

        res = sum(map(lambda e: e.amount, ActivityEntry.objects.filter(
            user__market__in=teams,
            activity=activity,
            creation_date__year=year,
            creation_date__month=month
        )))
        cache.set("activity_volumes:%s%s%s%s" % (''.join(teams), year, month, activity), str(res))
        return res

    @staticmethod
    def activity_volumes_last_12_months(teams, year=None, month=None, activity=None):
        from timetracker.utils.calendar_utils import last12months
        if activity is None:
            return [0 for _ in range(12)]

        if year is None: # pragma: no cover
            year = datetime.today().year
        if month is None: # pragma: no cover
            month = datetime.today().month

        dates = last12months(year, month)
        return (
            ActivityEntry.activity_volumes(teams, date.year, date.month, activity) \
            for date in dates
        )

    def save(self, *args, **kwargs):
        self.full_clean()
        cache.delete(
            "activity_volumes:%s%s%s%s" % (''.join(group_for_team(self.user.market)),
                                           self.creation_date.year,
                                           self.creation_date.month,

overtime/views.py
'''Views which are mapped from the URL objects in urls.py

    .. moduleauthor:: Aaron France <aaron.france@hp.com>

    :platform: All
    :synopsis: Module which contains view functions that are mapped from urls
'''

from functools import wraps

from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect

from timetracker.overtime.models import PendingApproval
from timetracker.tracker.models import Tbluser, TrackingEntry
from timetracker.tracker.models import Tblauthorization as tblauth
from timetracker.tracker.forms import TrackingEntryForm

from timetracker.utils.decorators import admin_check, loggedin
from timetracker.loggers import suspicious_log, email_log, error_log

def overtimereqs(f): # pragma: no cover
    @wraps(f)
    def inner(request, *args, **kwargs):
        entry = kwargs.get("entry")
        if not entry:
            return f(request, *args, **kwargs)
        auth_user = Tbluser.objects.get(
            id=request.session.get("user_id")
        )
        # if the provided entry ID is not here, then we're being duped.
        try:
            entry = PendingApproval.objects.get(entry_id=entry, closed=False)
        except PendingApproval.DoesNotExist:
            suspicious_log.critical(
                "An accept/edit check was made by %s for a non-existent entry." % auth_user.name()
            )
            raise Http404
        if not entry.entry.user_can_see(auth_user):
            raise Http404
        return f(request, *args, **kwargs)
    return inner

@overtimereqs
@admin_check
def accept_edit(request, entry=None): # pragma: no cover
    entry = PendingApproval.objects.get(entry_id=entry, closed=False)
    return render_to_response(
        "accept_edit.html",
        {
            "entry": entry,
            "form": TrackingEntryForm(instance=entry.entry)
        },
        RequestContext(request)
    )

@admin_check
def accepted(request): # pragma: no cover
    status = request.POST["status"] == "approved"
    pending_id = request.POST.get("pending_id")
    auth_user = Tbluser.objects.get(id=request.session.get("user_id"))
    if auth_user.can_close_approvals():
        PendingApproval.objects.get(id=pending_id).close(status)
    else:
        PendingApproval.objects.get(id=pending_id).tl_close(status)
    return render_to_response(
        "accept_edit_done.html",
        {
            "status": status
        },
        RequestContext(request)
    )

@admin_check
def approval_list(request): # pragma: no cover
    auth_user = Tbluser.objects.get(id=request.session.get("user_id"))
    approvals = PendingApproval.objects.filter(closed=False, approver=auth_user.get_administrator())
    return render_to_response(
        "approval_list.html",
        {
            "approvals": approvals
        },
        RequestContext(request)
    )

templates/accept_edit.html
{% extends "base.html" %}
{% block menubar %}
{% include "includes/get_nav.html" %}
{% endblock menubar %}
{% block header %}
<link href="{{ STATIC_URL }}calendar.css" type="text/css"
      rel="stylesheet" />
<link href="{{ STATIC_URL }}holidays.css" type="text/css"
      rel="stylesheet" />
{% endblock header %}
{% block title %}
Accept/Edit Tracking Entry
{% endblock title %}

{% block content %}
<!--[if IE 7]>
    <div id="isie" isie="true"></div>
    <![endif]-->
<!--[if IE]>
    <div id=IEFix>
      <![endif]-->
<table id="full-table-wrapper">
  <form action="{% url "overtime.views.accepted" %}" method="POST">
    <input type="hidden" name="pending_id" value="{{ entry.id }}" />
    {% csrf_token %}
    <tr>
      <th>
        <label for="id_user">Agent:</label>
      </th>
      <td>
        <input id="id_user" name="user" type="text" value="{{ entry.entry.user.name }}" readonly />
      </td>
    </tr>
    {{ form.as_table }}
    <tr>
      <th>
        <label for="status">Status:</label>
      </th>
      <td>
        <select id="status" name="status">
          <option value="approved" selected>Approved</option>
          <option value="denied">Denied</option>
        </select>
      </td>
    </tr>
    <tr>
      <th>
        <label for="submit">Submit:</label>
      </th>
      <td>
        <input id="submit" type="submit" />
      </td>
    </tr>
  </form>
</table>
<!--[if IE]>
    </div id=IEFix>
    <![endif]-->

{% endblock content %}

templates/admin_view.html
{% extends "base.html" %}

{% block header %}
<link href="{{ STATIC_URL }}calendar.css" type="text/css" rel="stylesheet" />
{% endblock header %}
{% block title %}
Overview - Timetracker
{% endblock title %}
{% block menubar %}
{% include "includes/get_nav.html" %}
{% endblock menubar %}
{% block content %}

<div id=IEroot>
<table id="user-table">
  <tr>
    <td valign="top">
      {{ employee_option_list|safe }}
    </td>
    <td valign="top">
      <div id="calendar_div"></div>
      <ul id="day_information">
        <li id="start_time"></li>
        <li id="end_time"></li>
        <li id="shiftlength"></li>
        <li id="breaks"></li>          
      </ul>
    </td>
    <td valign="top">
      <table id="admin-inner-cal">
        <thead>
          <tr>
            <th colspan="2">
              Your team's status:
            </th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
          <tr>
            <td class="{% cycle 'row-a' 'row-b' as rowcolour%}">
              <p>{{ employee.name }}</p>
            </td>
            <td class="{{ rowcolour }}">
              {{ employee.get_normalized_balance | safe }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>
    </td>
  </tr>
</table>
</div>

{% endblock content %}
{% block additional_javascript %}
<script type="text/javascript" src="{{ STATIC_URL }}js/admin_view.js"></script>
{% endblock additional_javascript %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{{ STATIC_URL }}stylesheet.css" type="text/css" rel="stylesheet" />
	<link type="text/css" href="{{ STATIC_URL }}jquery/css/ui-darkness/jquery-ui-1.10.3.custom.css" rel="stylesheet" />
    <link href="{{ STATIC_URL }}nav.css" type="text/css" rel="stylesheet" />
    {% block header %}
    {% endblock header %}
  </head>
    {% block menubar %}
    {% endblock menubar %}
    {% block content %}
    {% endblock %}
    {% block extra_content %}
    {% endblock extra_content %}
	<script type="text/javascript" src="{{ STATIC_URL }}jquery/js/jquery-1.10.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-migrate-1.2.1.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}jquery/js/jquery-ui-1.10.3.custom.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}jquery/js/csrf_protection.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}jquery/json2.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/validation.js"></script>
    {% block additional_javascript %}
    {% endblock additional_javascript %}

templates/calendar.html
{% extends "base.html" %}
{% block header %}
    <link href="{{ STATIC_URL }}calendar.css" type="text/css"
          rel="stylesheet" />
{% endblock header %}
{% block menubar %}

{% include "includes/get_nav.html" %}

    {% endblock menubar %}
    {% block title %}
    A month at a glance - Timetracker
    {% endblock title %}
    {% block content %}
    <div id=IEroot>
<table id="calendar-table">
  <tr>
    <td rowspan="2" valign="top">
      <table id="table-legend">
        <tr>
          <td class="empty holiday-button"></td><td>Empty</td>
        </tr>
        <tr>
          <td class="WKDAY holiday-button"></td><td>Work Day</td>
        </tr>
		<tr>
          <td class="LINKD holiday-button"></td><td>Linked Day</td>
        </tr>
        <tr>
          <td class="ROVER holiday-button"></td><td>Return for overtime</td>
        </tr>
        <tr>
          <td class="SICKD holiday-button"></td><td>Sickness</td>
        </tr>
        <tr>
          <td class="HOLIS holiday-button"></td><td>Holiday</td>
        </tr>
        <tr>
          <td class="PUABS holiday-button"></td><td>Public Hol</td>
        </tr>
        <tr>
          <td class="PUWRK holiday-button"></td><td>Work on holiday</td>
        </tr>
        <tr>
          <td class="SATUR holiday-button"></td><td>Saturday</td>
        </tr>
        <tr>
          <td class="RETRN holiday-button"></td><td>Returned day</td>
        </tr>
        <tr>
          <td class="WKHOM holiday-button"></td><td>Home</td>
        </tr>
        <tr>
          <td class="TRAIN holiday-button"></td><td>Training</td>
        </tr>
        <tr>
          <td class="DAYOD holiday-button"></td><td>Day on demand</td>
        </tr>
        <tr>
          <td class="PENDI holiday-button"></td><td>Approval Vacation</td>
        </tr>
        <tr>
          <td class="OTHER holiday-button"></td><td>Other</td>
        </tr>
      </table>
</td>
    <td>
      <form action="" id="add-form">
        {% csrf_token %}
        <fieldset class="entry-form" id="add-entry-fs">
          <legend class="fs-title">Add Entry</legend>
          <table>
            <tr>
              <th>
                <label for="add_entrydate">
                  Entry Date:
                </label>
              </th>
              <td>
                {{ addform.entry_date }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="add_starttime">
                  Start Time:
                </label>
              </th>
              <td>
                {{ addform.start_time }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="add_endtime">
                  End Time:
                </label>
              </th>
              <td>
                {{ addform.end_time }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="add_breaks">
                  Breaks:
                </label>
              </th>
              <td>
                {{ addform.breaks }}
              </td>
            </tr>
			<tr>
			  <th>
                <label for="add_link">
				  Link Date:
                </label>
              </th>
              <td>
                {{ addform.link_date }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="add_daytype">
                  Day Type:
                </label>
              </th>
              <td>
                <select class="change-el" id="add_daytype" name="daytype">
                  <option value="WKDAY">Work Day</option>
                  <option value="HOLIS">Vacation</option>
                </select>
              </td>
            </tr>
            <tr>
              <td></td>
              <td align="right">
                <input type="button"
                       onclick="ajaxCall('add')"
                       id="add_button"
                       value="Add"/>
              </td>
            </tr>
          </table>
        </fieldset>
      </form>
    </td>
    <td rowspan="2" width="400" valign="top">
      <div  id="calendar-entry">
        {{ calendar|safe }}
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <form action="#" method="POST" id="change-form">
        <input type="hidden" id="hidden_id"/>
        {% csrf_token %}
        <fieldset class="entry-form" id="change-entry-fs">
          <legend class="fs-title">Change Entry</legend>
          <table>
            <tr>
              <th>
                <label for="change_entrydate">
                  Entry Date:
                </label>
              </th>
              <td>
                {{ changeform.entry_date }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="change_starttime">
                  Start Time:
                </label>
              </th>
              <td>
                {{ changeform.start_time }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="change_endtime">
                  End Time:
                </label>
              </th>
              <td>
                {{ changeform.end_time }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="change_breaks">
                  Breaks:
                </label>
              </th>
              <td>
                {{ changeform.breaks }}
              </td>
            </tr>
			<tr>
			  <th>
                <label for="change_link">
				  Link Date:
                </label>
              </th>
              <td>
                {{ changeform.link_date }}
              </td>
            </tr>
            <tr>
              <th>
                <label for="change_daytype">
                  Day Type:
                </label>
              </th>
              <td>
                {{ changeform.daytype }}
              </td>
            </tr>
            <tr>
              <td></td>
              <td align="right">
                <input type="button"
                       onclick="deleteEntry()"
                       value="Delete" />

                <input type="button"
                       onclick="ajaxCall('change')"
                       value="Change" />
              </td>
            </tr>
          </table>
        </fieldset>
      </form>
    </td>
  </tr>
</table>
<div id="doculink"> <a href="{{ doculink }}user_guide.html">Documentation</a> </div>
{% endblock content %}
{% block additional_javascript %}
    <script type="text/javascript">
        $("#change-entry-fs")
            .find("label")
            .each( function () {
                if ($(this).attr("for") === "change_daytype") {
                    $(this).hide();
                }
            });
        $("#add-entry-fs")
            .find("label")
            .each( function () {
                if ($(this).attr("for") === "add_daytype") {
                    $(this).hide();
                }
            });
        $("#change_daytype").hide();
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery/js/timepicker.js">
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/calendar.js">
    </script>
{% endblock additional_javascript %}

templates/fail.html
<html>
  <body>
    <title>{{ fail }}</title>
    <p>You have failed to log in due to: {{ reason }}</p>
    <h3>{{ helpfultext|safe }}</h3>
  </body>
</html>